// backend/routes/index.js
const express = require("express");
const authRoutes = require("./user/authRoutes");
const logProductRoutes = require("./inventory/logProductRoutes");
const productsRoute = require("./inventory/productRoutes");
const customersRoute = require("./customers/customerRoutes");
const paketRoute = require("./customers/paketRoutes");
const mitraRoute = require("./customers/mitraRoutes");

const router = express.Router();
router.use("/user", authRoutes); // jadi /api/user/…
router.use("/records", logProductRoutes); // jadi /api/records/…
router.use("/products", productsRoute); // jadi /api/products/…
router.use("/customers", customersRoute); // jadi /api/customers/....
router.use("/paket", paketRoute); // Jadi /api/paket/...
router.use("/mitra", mitraRoute); // Jadi /api/mitra/...

module.exports = router;
